learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),#Colle tout URL qui commence avec le mot users
    path('', include('learning_logs.urls'))
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path #permet d'importer la fonction path

from . import views# permet d'importer le module views présent dans learning_logs

app_name = 'learning_logs' #permet de distinguer l'urls.py d'autres urls.py d'autres applic° ds le projet
urlpatterns = [	 
	#liste de pages individuelles demandés sur l'appli learning_logs
	path('', views.index, name='index'),#trois arguments : 
										# '' :relie l'URL demandé à une vue, remplaçant l'url de base (http://localhost:8000/) 
										# views.index : appele une fonction dans views.py (ici index()) quand l'URL demandé est trouvé 
	#Page that shows all topics. 
	path('topics/', views.topics, name ='topics'),
	# Detail page for a single topic. 
	path('topics/<int:topic_id>/', views.topic, name='topic'), #1e argument = regarde ce qui vient après les URL qui ont le mot topics et y ajoute un entier entre deux slashs
	# Page for adding a new topic
	path('new_topic/', views.new_topic, name = 'new_topic'),
	# Page for adding a new entry
	path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	# Page for editing an entry. 
	path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL patterns for users"""

# importe les fonctions : 
## 1) path pour router les adresses
## 2) include pour ajouter les URL d'authentification par défaut que Django a défini
from django.urls import path, include 

#importe à partir de users les modules views pour écrire notre propre view pour la page d'inscription
from . import views


app_name = 'users' #variable permettant à Django de distinguer les URL patterns pour l'utilisateur des URL 
				   #appartenant à d'autres applications (ex : learning_log)
urlpatterns = [
	# Include default auth urls. 
	path('', include('django.contrib.auth.urls')),# colle à l'URL http://localhost:8000/users/login
												  ## users : demande à Django de regarder dans users/urls.py
												  ## login : appelle Django à envoyer des requêtes à la vue login par défaut du framework
	# Registration page. 
	path('register/', views.register, name='register'), # colle à l'URL http://localhost:8000/users/registers											  
														# envoie des requêtes à la fonction register() que nous avons écrit 
								
] 

learning_logs/models.py
from django.db import models

#importation du modèle User à partir de django.contrib.auth
from django.contrib.auth.models import User


# Create your models here.
# Model = class

class Topic(models.Model):#Which inherit from Model, parent class included in Django
						  #defines the basic functionality of a model. 
	"""A topic the user is learning about"""
	text = models.CharField(max_length=200)#Piece of data made of characters with a limit 
	date_added = models.DateTimeField(auto_now_add=True)#Piece of data which record
														#date and time
	owner = models.ForeignKey(User, on_delete=models.CASCADE)#Champ propriétaire, correspondant au pseudo de l'utilisateur postant le topic													
	def __str__(self):#Attribute used by default when there is information about a topic
		"""Return a string representation of the model."""
		return self.text

class Entry(models.Model):
	"""Something specific learned about a topic"""
	topic = models.ForeignKey(Topic, on_delete = models.CASCADE)#Connect to each entry to a specific topic
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)#Present entries in chronological order
	

	class Meta:#Holds extra information for managing a model
		verbose_name_plural = 'entries'

	def __str__(self):
		"""Return a string representation of the model"""
		if len(self.text)> 50:#Si le texte a plus de 50 caractères ajouter une ellipse après les 50 1er charactères
			return self.text[:50] + "..."#Show just the first 50 character of text

		else: #Sinon tout retourner 
			return self.text

learning_logs/forms.py
from django import forms 

#Usage des modèles Topic et Entry dans models.py
from .models import Topic, Entry


class TopicForm(forms.ModelForm): 
	"""Classe indiquant sur quel modèle le formulaire doit se baser et quels champs y inclure """
	class Meta: 
		model = Topic # utilisation du modèle Topic
		fields = ['text'] # inclusion du champ de texte
		labels = {'text': ''} # empêche d'utiliser des labels pour le champ de texte

class EntryForm(forms.ModelForm): 
	"""Classe indiquant sur quel modèle le formulaire doit se baser et quels champs y inclure """
	class Meta: 
		model = Entry # utilisation du modèle Topic
		fields = ['text'] # inclusion du champ de texte
		labels = {'text': 'Entry:'} # empêche d'utiliser des labels pour le champ de texte
		widgets = {'text': forms.Textarea(attrs={'cols': 80})} #un élément de formulaire HTML 
													 #(ex: boite de texte à une ligne, zone de texte à plusieurs lignes, liste déroulante)
													 #forms.Textarea(attrs={'cols': 80}) : aire de texte à 80 colonnes de large au lieu des 40 par défaut 

learning_logs/views.py
"""
Prends une information à partir d'une demande,
prépare les données génératrices de page, 
envoie les données au navigateur en utilisant une template 
(définit l'apparence de la page)
"""

# render : importe la fonction render(), qui effectue le rendu de la
## réponse en fonction des données fournies par les vues.
# redirect : importe la fonction redirect(), qui redirige l'utilisateur à la page topics 
## après qu'il ait posté son topic

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required 

from .models import Topic, Entry #Importation des models Topic et Entry de models.py
from .forms import TopicForm, EntryForm #Importation des formulaires Topic et Entry de forms.py
from django.http import Http404 # Importation de l'exception HTTP404, erreur standar qui est retourné quand une ressource demandé n'existe pas ds un serveur 



def index(request):
	"""The home page for Learning Log."""
	return render(request, 'learning_logs/index.html') #rend la réponse inspiré des données fournis par les vues
													   #Deux arguments:
													   ##1) request : l'objet request original 

@login_required # decorateur qui vérifie si un utilisateur est connecté AVANT l'exécution de la fonction topics.
				## Si l'utilisateur n'est pas connecté, il est redirigé à la page de connexion  													   
def topics(request): #request = objet requête reçu du serveur 
	"""Show all topics."""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added') # assignation des données des objets Topic, trié par dates et visible seulement par le créateur 
	context = {'topics':topics}# dictionnaire où les clés sont des noms utilisés dans le template pour accéder aux données voulues (ici topic) 
	return render(request, 'learning_logs/topics.html', context)#construction de la page 													   
																##2) un modèle utilisé par Django pour construire la page

@login_required
def topic(request, topic_id): #topic id = partie de l'URL venant après /topics/
	"""Show a single topic and all its entries."""
	topic = Topic.objects.get(id=topic_id) #requete qui récupère le topic
	# Make sure the topic belongs to the current user. 
	if topic.owner != request.user:
		raise Http404

	entries = topic.entry_set.order_by('-date_added') #requête qui prend les entrées associés au topics, chronologiq-t
	context = {'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context) #stocke le topic et entrées dans un dict context et le retourne dans topic.html

@login_required
def new_topic(request):
	"""Add a new topic."""
	if request.method != 'POST': #si la requête est de type GET 
		# No data submitted; create a blank form
		form = TopicForm() #Utilisation de la classe TopicForm

	else: #si la requête est de type POST 
		#POST data submitted; process data.
		form = TopicForm(data=request.POST) #Contient l'information entrée par l'utilisateur 
		if form.is_valid():#Si les types de champs utilisés sont en accord avec les données, sauvegarder ces derniers
			new_topic = form.save(commit=False) #modifie le nouveau sujet avant de le passer à la base de données (BDD)
			new_topic.owner = request.user #règle la propriété du nouveau topic à l'utilisateur actuel 
			new_topic.save() #sauvegarde sur le topic défini
			return redirect('learning_logs:topics')#redirection du navigateur utilisateur vers la page topics 

	# Display a blank or invalid form. 
	context = {'form': form} #dictionnaire où est envoyé le formulaire pour l'envoyer au template
	return render(request, 'learning_logs/new_topic.html', context)
	
@login_required
def new_entry(request, topic_id):
	"""Add a new entry for a particular topic."""
	topic = Topic.objects.get(id=topic_id)#Topic relevé pour faire un rendu de la page et enclencher un processus dans les données des formulaires
	
	if request.method != 'POST': # Si la méthode de requête est GET, il ne doit rien y avoir dans le formulaire Entry
		#No data submitted; create a blank form. 
		form = EntryForm() 
	else: 
		# POST data submitted; process data.
		form = EntryForm(data=request.POST) 
		if form.is_valid():
			new_entry = form.save(commit=False)#Création d'un objet pour une nouvelle entry, sans sauvegarde
			new_entry.topic = topic #attribut opic de new_entry affecté au topic que nous avons tiré de la base de donnée au début de la fonction 
			new_entry.save() #sauvegarde de l'entry à la database avec le topic correctement associé 
			return redirect('learning_logs:topic', topic_id=topic_id) #A besoin de deux arguments : le nom de la vue que l'on veut rediriger et l'argumet dont la fonction vue requiert

	# Display a blank or invalid form. 
	context = {'topic':topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	"""Edit an existing entry."""
	entry = Entry.objects.get(id=entry_id) #Affectaion de l'entrée-objet que l'utilisateur veut éditer 
	topic = entry.topic #Affectation du topic associé avec ette entrée 
	# Si le propriétaire du topic n'est pas l'utilisateur qui tente d'éditer, élever une erreur
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		#Initial request; pre-fill form with the current entry. 
		form = EntryForm(instance=entry) #Crée le formulaire pré-rempli avec les informations tiré de entry

	else:
		#POST data submitted; process data. 
		form = EntryForm(instance=entry, data=request.POST) #Crée un formulaire basé sur les informations associé avec entry
															#mis à jour avec n'importe quelle donnée pertinente partant de request.POST 
		if form.is_valid(): 
			# Si le formulaire est valide, sauvegarder et rediriger vers la page HTML topic, l'entrée mis à jour
			form.save() 
			return redirect('learning_logs:topic', topic_id=topic.id)

	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'learning_logs/edit_entry.html', context)

	

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %} <!-- Chargement des templates disponibles dans Bootstrap --> 

<!doctype html> <!-- Déclaration du fichier comme document HTML --->
<html lang="en"> <!--- Langage d'écriture du docment -->
<head> <!-- Début de la tête du fichier HTML -->
	<!-- Montre tout ce dont a besoin le navigateur pour afficher la page correctement --> 
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Learning Log</title> <!-- Affiche Learning Log comme titre dans la barre du navigateur de l'onglet -->

	{% bootstrap_css %}<!--Dit à Django d'inclure tous les fichers stylistiques Bootstrap-->
	{% bootstrap_javascript jquery='full' %}<!-- Active tous les comportements interactifs que l'on peut utiliser sur une page (ex : barre de navigation coulissante)-->

</head>
<body>
	<!-- Contient le contenu que les utilisateurs verront dans la page.-->
		<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border"><!--Décrit la section des liens de la page de navigation d'après les règles de style Bootstrap définis par les sélecteurs (ex : navbar)-->

			<a class="navbar-brand" href="{% url 'learning_logs:index'%}">Learning Log</a><!--Met le nom du projet en haut à gauche de la barre de navigation et le transforme en lien distinct des autres liens à la page d'acceuil--> 

			<!-- Boutton qui apparait si la fenêtre de navigation est trop étroit pour afficher toute la barre de navigation horizontalement-->

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span></button>
			<div class="collapse navbar-collapse" id="navbarCollapse"><!--Nouvelle section de la barre de navigation-->
				<ul class="navbar-nav mr-auto"><!--Définition d'un nouveau set de liens (ici la page Topics)-->
					<li class="nav-item">
						<a class="nav-link" href="{% url 'learning_logs:topics'%}">
							Topics</a></li>
				</ul>
				<ul class="navbar-nav ml-auto">
				<!--Définition d'un nouveau set de liens (ici la page de connexion)-->
					<!--ml-auto : examination des éléments dans la barre de navigation, création d'une marge gauche qui repousse le set de liens vers le côté droit de l'écran. -->  
					{% if user.is_authenticated %}
						<li class="nav-item">
							<!-- span : stylise des parties de texte, d'éléments d'une page qui font partie d'une ligne longue -->
							<span class="navbar-text">Bonjour, {{ user.username }}.</span>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'users:logout' %}">Se déconnecter</a>
						</li>
					{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{% url 'users:register' %}">S'enregistrer</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{% url 'users:login' %}">Se connecter</a></li>	
					{% endif %}
				</ul>
			</div>

		</nav>

		<!-- main : utilisé pour les parties les plus significatives du corps d'une page -->
		<main role="main" class="container">
			<!-- pb-2 : Ajout d'espace entre le contenu d'un élément et sa bordure -->
			<!-- mb-2 : espace entre la bordure d'un élément et les autres éléments sur la page -->
			<!-- border-bottom : sélecteur qui donne une bordure mince au fond d'un élément stylisé --> 
			<div class="pb-2 mb-2 border-bottom">
				<!-- page_header pour titrer la majorité des pages-->
				{% block page_header %}
					<!-- jumbotron : large boite qui contient une description générale du projet et appelle au visiteur à l'utilisation -->
					<div class="jumbotron">
						<!-- h1 : header de premier niveau -->
						<!-- display-3 : sélecteur ajoutant à ce header une plus mince et grande apparence -->
						<h1 class="display-3">Suivez votre apprentissage.</h1>

						<!-- Inclusion du message ajoutant ce que l'utilisateur peut faire -->
						<p class="head">Créez votre propre journal d'apprentissage, et tenez une liste des sujets sur lesquels vous vous renseignez. Chaque fois que vous apprenez quelque chose de nouveau sur un sujet, faites une entrevue résumant ce que vous avez appris.</p>

						<!-- Creation du bouton invitant l'utilisateur à s'enregistrer 
						- &raquo : entité HTML qui affiche "">>"" -->
						<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">S'enregistrer &raquo</a>
					</div>
				{% endblock page_header %}

			</div>
			<!-- Content le block contenu -->
			<div>
				{% block content %}{% endblock content %}
			</div>
		</main>
	
	</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
<!-- Charger le template bootstrap4 dans la page html -->
{% load bootstrap4 %}

<!-- Dit à l'utilisateur la fonction de la page -->
{% block page_header %}
	<h2>Modifiez l'entrée.</h2>
{% endblock page_header %}

{% block content %}

	<form method='post' action="{% url 'learning_logs:edit_entry' entry.id %}" class="form"> <!-- argument action : envoie le formulaire à la fonction edit_entry pour son traitement -->
		{% csrf_token %}
		{% bootstrap_form form %} <!--- Affiche les éléments du formulaire en format paragraphe avec les règles stylistiques de la template bootstrap4 --->
		{% buttons %}
			<button name="submit" class="btn btn-primary">Sauvegarder les changements.</button> <!-- Sauvegarde de l'édit -->
		{% endbuttons %}
		
	</form>

{% endblock content %} 

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %} <!--- Demande à Django d'hériter du lien Learning Logs et lien URL --->

{% block content %}
<p>Learning Log vous aide à garder une trace de votre apprentissage, quel que soit le sujet sur lequel vous vous renseignez.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
<!-- Charger le template bootstrap4 dans la page html -->
{% load bootstrap4 %}

<!-- Dit à l'utilisateur la fonction de la page -->
{% block page_header %}
	<h2>Ajouter une nouvelle entrée.</h2>
{% endblock page_header %}



{% block content %}
	
	<form method="post" action="{% url 'learning_logs:new_entry' topic.id %}" class="form"><!-- Associe la nouvelle entrée avec le topic correspondant par la fonction vue -->
		{% csrf_token %}
		{% bootstrap_form form %} <!--- Affiche les éléments du formulaire en format paragraphe avec les règles stylistiques de la template bootstrap4 --->
		{% buttons %}
			<button name="submit" class="btn btn-primary">Ajouter une entrée</button> <!--- Crée un boutton "soumettre" --->
		{% endbuttons %}
	</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
<!-- Charger le template bootstrap4 dans la page html -->
{% load bootstrap4 %}

<!-- Dit à l'utilisateur la fonction de la page -->
{% block page_header %}
	<h2>Ajouter un nouveau sujet.</h2>
{% endblock page_header %}

{% block content %}
	<form method="post" action="{% url 'learning_logs:new_topic' %}" class="form"> <!--- action : argument disant au navigateur où envoyer les données soumis dans le formulaire, ici dans la fonction vue new_topic() --->
		{% csrf_token %} <!--- Préviens toute attaque malveillante tentant un accès non autorisé au serveur --->
		{% bootstrap_form form %} <!--- Affiche les éléments du formulaire en format paragraphe avec les règles stylistiques de la template bootstrap4 --->
		{% buttons %}
			<button name="submit" class="btn btn-primary">Ajouter un sujet</button> <!--- Crée un boutton "soumettre" --->
		{% endbuttons %}
	</form>

{% endblock content %}


		

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h3>{{ topic }}</h3><!--- Montre la rêquete topic inclus dans le dictionnaire context --->
{% endblock page_header %}

{% block content %}
	<p>
		<a href="{% url 'learning_logs:new_entry' topic.id %}">Ajouter une nouvelle entrée</a>
	</p><!-- Ajout d'un lien à la page new_entry sur chaque page de topic-->

	
	{% for entry in entries %}
		<!-- card : permet d'utiliser des styles prédéfinis, flexibles parfait pour afficher les entrées d'un topic. 
			Il a 2 éléments imbriqués : un pour tenir l'horodatage/lien pour éditer l'entrée, l'autre pour tenir le corps de l'entrée -->
		<div class="card mb-3">
			<h4 class="card-header">
				{{ entry.date_added|date:'M d, Y H:1' }} <!--- Horodatage des entrées au format Mois jour, Année heure ---> 
				<!-- small : tag qui fait apparaitre le lien "édition" plus petit que l'horodatage-->
				<small><a href="{% url 'learning_logs:edit_entry' entry.id %}">Modifier l'entrée</a></small>
			</h4>
			<!-- Place le texte de l'entrée dans une boite simple -->
			<div class="card-body">
				{{ entry.text|linebreaks }}
			</div>
		</div>

			</p><!-- Incorporation du lien éditer après chaque date de création d'entrée et son texte -->
		</li>
	{% empty %}<!--- affiche un message informant l'utilisateur qu'il n'y a pas d'entrées faits--->
			<li>Il n'y a pas encore d'entrées pour ce sujet.</li>
	{% endfor %}


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}<!--- Hérite des données de la base.html---> 

{% block page_header %}
	<!-- Entête stylisant Topics-->	
	<h1>Sujets</h1>
{% endblock page_header %}

{% block content %}
	<ul> <!--- Liste désordonnée --->
		{% for topic in topics %} 
	    	<!-- Stylisation d'entête de taille 3 -->
	    	<li><h3>
	    		<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
	    	</h3></li> <!--- Deux accolades pour print le texte du topic --->
	 		{% empty %} <!--- Pas d'item dans la liste = avertissement --->
	    	<li><h3>Aucun sujet n'a encore été ajouté.</h3></li>
	  	{% endfor %}
	</ul>

	<h3><a href="{% url 'learning_logs:new_topic' %}">Ajouter un nouveau sujet</a></h3>
{% endblock content %}